// SPDX-License-Identifier: MIT 
pragma solidity ^0.8.0;

contract BuyCookies{
  // Event som skickar ett meddelande köper kakor...

  // Struct för att definiera ett meddelande...

  // Address till ägaren som är payable...

  // Array med meddelanden ifrån kunder...

  // Constructor...
  
  // Funktion som returnerar meddelandena...

  // Funktion för att kunna köpa kakor, tar argument name och message...

  // Funktion som gör att jag som ägare kan få tag i betalningarna...


}